# Load packages -----------------------------------------------------

if(!require("shiny")) install.packages("shiny", dependencies = TRUE)
if(!require("tools")) install.packages("tools", dependencies = TRUE)
if(!require("stringr")) install.packages("stringr", dependencies = TRUE)
if(!require("tidyverse")) install.packages("tidyverse", dependencies = TRUE)
if(!require("ggthemes")) install.packages("ggthemes", dependencies = TRUE)
if(!require("ggpubr")) install.packages("ggpubr", dependencies = TRUE)
if(!require("shinythemes")) install.packages("shinythemes", dependencies = TRUE)
if(!require("rsconnect")) install.packages("rsconnect", dependencies = TRUE)
if(!require("shinyWidgets")) install.packages("shinyWidgets", dependencies = TRUE)
if(!require("shinydashboard")) install.packages("shinydashboard", dependencies = TRUE)
if(!require("shinyalert")) install.packages("shinyalert", dependencies = TRUE)
if(!require("leaflet")) install.packages("leaflet", dependencies = TRUE)
if(!require("devtools")) install.packages("devtools", dependencies = TRUE)
if(!require("dashboardthemes")) install_github("nik01010/dashboardthemes", dependencies = TRUE)
if(!require("rmarkdown")) install.packages("rmarkdown", dependencies = TRUE)


rm(list=ls())
# Load data ---------------------------------------------------------
biota <- read_csv("table_biota_all_variables_YSOUZA_10-02-2020.csv")

# Define UI ---------------------------------------------------------


shinyUI(
  dashboardPage(title = "DEFAU-BIOTA dataset", skin = "green",
    dashboardHeader(title = "DEFAU-BIOTA", titleWidth = 300),
    dashboardSidebar(width = 300,
      useShinyalert(),
      sidebarMenu(
      menuItem("Home", tabName = "home", icon = icon("home")),
      menuItem("Sampled areas", icon = icon("globe-americas"),
               menuSubItem(text = "Description", tabName = "description", icon = icon("th-list")),
               menuSubItem(text = "Map", tabName = "map", icon = icon("map-marked-alt"))),
      menuItem("Data table", tabName = "datatable", icon = icon("database")),
      menuItem("Data exploration", tabName = "data_exploration", icon = icon("chart-line")),
      menuItem("Gallery", icon = icon("images"),
               menuSubItem(text = "Sampling Design", tabName = "sampling_design", icon = icon("drafting-compass")),
               menuSubItem(text = "Fieldworks", tabName = "fielworks", icon = icon("compass")),
               menuSubItem(text = "Camera Traps", tabName = "camera_traps", icon = icon("camera")),
               menuSubItem(text = "Social Media", tabName = "social_media", icon = icon("project-diagram"))
               ),
      menuItem("Media", icon = icon("comments"),
               menuSubItem(text = "Media", tabName = "media", icon = icon("comment-alt")),
               menuSubItem(text = "Publications", tabName = "publications", icon = icon("file-pdf"))),
      menuItem("Contacts", tabName = "contacts", icon = icon("paper-plane")),
      textOutput("counter"))
    ),
    dashboardBody(
      shinyDashboardThemes(theme = "poor_mans_flatly"),
      tabItems(
        tabItem(tabName = "data_exploration",
                fluidRow(
                  box(
                    #background = "black",
                    selectInput(inputId = "y", 
                                label = "Y-axis:",
                                choices = c("Altitude" = "Elevation", 
                                            "Latitude" = "Latitude",
                                            "Seedlings richness" = "Richness",
                                            "Seedlings abundance" = "Abundance",
                                            "Seedlings density" = "Density",
                                            "Shannon index diversity" = "D_Shannon",
                                            "Simpson index diversity" = "D_Simpson",
                                            "Canopy cover (%)" = "Canopy_cover",
                                            "Total adult trees outside plots" = "N_M_Trees_adult",
                                            "Total adult Euterpe edulis outside plots" = "N_M_Eedulis_adult",
                                            "Functional richness" = "FRic",
                                            "Functional evenness" = "FEve",
                                            "Functional diversity" = "FDiv",
                                            "Functional dispersion" = "FDis",
                                            "Rao's Quadratic Entropy - Functional diversity index" = "Rao",
                                            "Leaf thickness" = "leaf_thickness",
                                            "Seed mass" = "seed_mass",
                                            "Leaf area" = "leaf_area",
                                            "Specific leaf area" = "sla",
                                            "Seed length" = "seed_length",
                                            "Carbon and nitrogen ratio" = " carbon_nitro",
                                            "Total leaf damage index" = "leaf_demage",
                                            "Leaf damage index by external chewer" = "ME",
                                            "Leaf damage index by internal chewer" = "MI",
                                            "Leaf damage index by pathogens" = "PAT",
                                            "Leaf damage index by miners" = "MIN",
                                            "Leaf damage index by galls" = "GAL", 
                                            "Total Euterpe edulis seed offered" = "Ed_seeds_available",
                                            "Total Euterpe edulis seed preyed" = "Ed_seeds_preyed",
                                            "Total cameras trap efforts (hours) (seeds predation)" = "Ed_predation_efforts_hours",
                                            "Green House Gases Mean replicates" = "GHG_Rep",
                                            "Mean CH4" = "GHG_CH4",
                                            "Mean CO2 (mg)" = "GHG_CO2",
                                            "Mean N2O (mg)" = "GHG_N2O",
                                            "pH in water" = "pH_H2O",
                                            "pH in Calcium Chloride" = "pH_CaCl2",
                                            "Sum of the bases Ca2+, Mg2+, K+, Na+" = "SB",
                                            "Cation exchange capacity" = "CEC",
                                            "Base saturation" = "V",
                                            "Soil aluminum saturation" = "m",
                                            "Phosphorus Mehlich 1" = "P",
                                            "Potassium Mehlich 1" = "K",
                                            "Calcium KCl 1 mol.L-¹" = "Ca",
                                            "Magnesium KCl 1 mol.L-¹" = "Mg",
                                            "Aluminum KCl 1 mol.L-¹" = "Al",
                                            "Potencial acidity Calcium Acetate" = "H_Al",
                                            "Organic matter - Sodium Dicromate solution in Sulphuric acid determined by colorimetry" = "OM",
                                            "Total sand content (Buyoucos, densimeter)" = "Total_sand",
                                            "Silt content (Buyoucos, densimeter)" = "Silt",
                                            "Clay content (Buyoucos, densimeter)" = "Clay",
                                            "Levels of sand and clay content" = "Texture",
                                            "Total camera trap effort (day)" = "effort_cam_day_summed",
                                            "Total species richness" = "ttl_spp_rich",
                                            "Total medium and large-sized mammals species richness" = "med_lar_mamm_spp_rich",
                                            "Total small mammals species richness" = "small_mamm_spp_rich",
                                            "Total birds species richness" = "birds_spp_rich",
                                            "Total functional group richness" = "ttl_fg_rich",
                                            "Total medium and large-sized mammals functional group richness" = "med_lar_mamm_fg_rich",
                                            "Total small mammals functional group richness" = "small_mamm_fg_rich",
                                            "Total birds functional group richness" = "birds_fg_rich",
                                            "Birds functional group 1 individual frequency" = "birds_1_ttl_abnd",
                                            "Birds functional group 2 individual frequency" = "birds_2_ttl_abnd",
                                            "Birds functional group 3 individual frequency" = "birds_3_ttl_abnd",
                                            "Birds functional group 4 individual frequency" = "birds_4_ttl_abnd",
                                            "Herbivores functional group 1 individual frequency" = "herbivore_1_ttl_abnd",
                                            "Herbivores functional group 2 individual frequency" = "herbivore_2_ttl_abnd",
                                            "Herbivores functional group 3 individual frequency" = "herbivore_3_ttl_abnd",
                                            "Marsupials functional group 1 individual frequency" = "marsupial_1_ttl_abnd",
                                            "Marsupials functional group 2 individual frequency" = "marsupial_2_ttl_abnd",
                                            "Marsupials functional group 3 individual frequency" = "marsupial_3_ttl_abnd",
                                            "Mesopredator functional group 1 individual frequency" = "meso_1_ttl_abnd",
                                            "Others functional group 1 individual frequency" = "others_1_ttl_abnd",
                                            "Predators functional group 1 individual frequency" = "predator_1_ttl_abnd",
                                            "Predators functional group 2 individual frequency" = "predator_2_ttl_abnd",
                                            "Rodents functional group 1 individual frequency" = "rodent_1_ttl_abnd",
                                            "Rodents functional group 2 individual frequency" = "rodent_2_ttl_abnd",
                                            "Rodents functional group 3 individual frequency" = "rodent_3_ttl_abnd",
                                            "Rodents functional group 4 individual frequency" = "rodent_4_ttl_abnd",
                                            "All medium and large-sized mammals functional group individual frequency" = "all_med_lar_abn",
                                            "All small mammals functional group individual frequency" = "all_small_abn",
                                            "All birds functional group individual frequency" = "all_birds_abn",
                                            "Cabassous sp. individual frequency" = "Cabassous_sp__ttl_abnd",
                                            "Cuniculus paca individual frequency"= "Cuniculus_paca_ttl_abnd",
                                            "Dasyprocta leporina individual frequency"= "Dasyprocta_leporina_ttl_abnd",
                                            "Dasypus novemcinctus individual frequency" = "Dasypus_novemcinctus_ttl_abnd",
                                            "Dasypus_sp. individual frequency" = "Dasypus_sp__ttl_abnd",
                                            "Eira barbara individual frequency" = "Eira_barbara_ttl_abnd",
                                            "Euphractus sexcinctus individual frequency" = "Euphractus_sexcinctus_ttl_abnd",
                                            "Leopardus guttulus individual frequency" = "Leopardus_guttulus_ttl_abnd",
                                            "Leopardus pardalis individual frequency" = "Leopardus_pardalis_ttl_abnd",
                                            "Leopardus wiedii individual frequency" = "Leopardus_wiedii_ttl_abnd",
                                            "Leopardus sp. individual frequency" = "Leopardus_sp__ttl_abnd",
                                            "Mazama sp. individual frequency" = "Mazama_sp__ttl_abnd",
                                            "Myrmecophaga tridactyla individual frequency" = "Myrmecophaga_tridactyla_ttl_abnd",
                                            "Nasua nasua individual frequency" = "Nasua_nasua_ttl_abnd",
                                            "Pecari tajacu individual frequency" = "Pecari_tajacu_ttl_abnd",
                                            "Puma concolor individual frequency" = "Puma_concolor_ttl_abnd",
                                            "Puma yagouaroundi individual frequency" = "Puma_yagouaroundi_ttl_abnd",
                                            "Sylvilagus brasiliensis individual frequency" = "Sylvilagus_brasiliensis_ttl_abnd",
                                            "Tamandua tetradactyla individual frequency" = "Tamandua_tetradactyla_ttl_abnd",
                                            "Tapirus terrestris individual frequency" = "Tapirus_terrestris_ttl_abnd",
                                            "Tayassu pecari individual frequency" = "Tayassu_pecari_ttl_abnd",
                                            "Birds functional group 1 biomass (kg)" = "birds_1_fg_kg",
                                            "Birds functional group 2 biomass (kg)"= "birds_2_fg_kg",
                                            "Birds functional group 3 biomass (kg)" = "birds_3_fg_kg",
                                            "Birds functional group 4 biomass (kg)" = "birds_4_fg_kg",
                                            "Birds herbivore group 1 biomass (kg)" = "herbivore_1_fg_kg",
                                            "Birds herbivore group 2 biomass (kg)" = "herbivore_2_fg_kg",
                                            "Birds herbivore group 3 biomass (kg)" = "herbivore_3_fg_kg",
                                            "Marsupial functional group 1 biomass (kg)" = "marsupial_1_fg_kg",
                                            "Marsupial functional group 2 biomass (kg)" = "marsupial_2_fg_kg",
                                            "Marsupial functional group 3 biomass (kg)" = "marsupial_3_fg_kg",
                                            "Mesopredator functional group 1 biomass (kg)" = "meso_1_fg_kg",
                                            "Others functional group 1 biomass (kg)" = "others_1_fg_kg",
                                            "Predator functional group 1 biomass (kg)" = "predator_1_fg_kg",
                                            "Predator functional group 2 biomass (kg)" = "predator_2_fg_kg",
                                            "Rodent functional group 1 biomass (kg)" = "rodent_1_fg_kg",
                                            "Rodent functional group 2 biomass (kg)" = "rodent_2_fg_kg",
                                            "Rodent functional group 3 biomass (kg)" = "rodent_3_fg_kg",
                                            "Rodent functional group 4 biomass (kg)" = "rodent_4_fg_kg",
                                            "Total medium and large-sized mammals functional group biomass (kg)" = "all_med_lar_bmss_kg",
                                            "Total small mammals functional group biomass (kg)" = "all_small_bmss_kg",
                                            "Total birds functional group biomass (kg)" = "all_birds_bmss_kg",
                                            "Birds functional group 1 biomass (kg) by camera efforts (day)" = "birds_1_fg_kg_cam_effort",
                                            "Birds functional group 2 biomass (kg) by camera efforts (day)"= "birds_2_fg_kg_cam_effort",
                                            "Birds functional group 3 biomass (kg) by camera efforts (day)" = "birds_3_fg_kg_cam_effort",
                                            "Birds functional group 4 biomass (kg) by camera efforts (day)" = "birds_4_fg_kg_cam_effort",
                                            "Herbivore functional group 1 biomass (kg) by camera efforts (day)" = "herbivore_1_fg_kg_cam_effort",
                                            "Herbivore functional group 2 biomass (kg) by camera efforts (day)" = "herbivore_2_fg_kg_cam_effort",
                                            "Herbivore functional group 3 biomass (kg) by camera efforts (day)" = "herbivore_3_fg_kg_cam_effort",
                                            "Marsupials functional group 1 biomass (kg) by camera efforts (day)" = "marsupial_1_fg_kg_cam_effort",
                                            "Marsupials functional group 2 biomass (kg) by camera efforts (day)" = "marsupial_2_fg_kg_cam_effort",
                                            "Marsupials functional group 3 biomass (kg) by camera efforts (day)" = "marsupial_3_fg_kg_cam_effort",
                                            "Mesopredator functional group 1 biomass (kg) by camera efforts (day)" = "meso_1_fg_kg_cam_effort",
                                            "Others functional group 1 biomass (kg) by camera efforts (day)" = "others_1_fg_kg_cam_effort",
                                            "Predators functional group 1 biomass (kg) by camera efforts (day)" = "predator_1_fg_kg_cam_effort",
                                            "Predators functional group 2 biomass (kg) by camera efforts (day)" = "predator_2_fg_kg_cam_effort",
                                            "Rodents functional group 1 biomass (kg) by camera efforts (day)" = "rodent_1_fg_kg_cam_effort",
                                            "Rodents functional group 2 biomass (kg) by camera efforts (day)" = "rodent_2_fg_kg_cam_effort",
                                            "Rodents functional group 3 biomass (kg) by camera efforts (day)" = "rodent_3_fg_kg_cam_effort",
                                            "Rodents functional group 4 biomass (kg) by camera efforts (day)" = "rodent_4_fg_kg_cam_effort",
                                            "Total medium and large-sized mammals functional group biomass (kg) by camera efforts (day)" = "all_med_lar_bmss_kg_cam_effort",
                                            "Total small mammals functional group biomass (kg) by camera efforts (day)" = "all_small_bmss_kg_cam_effort",
                                            "Total birds functional group biomass (kg) by camera efforts (day)" = "all_birds_bmss_kg_cam_effort",
                                            "Cabassous sp. biomass (kg)" = "Cabassous_sp__kg",
                                            "Cuniculus paca biomass (kg)" = "Cuniculus_paca_kg",
                                            "Dasyprocta leporina biomass (kg)" = "Dasyprocta_leporina_kg",
                                            "Dasypus novemcinctus biomass (kg)" = "Dasypus_novemcinctus_kg",
                                            "Dasypus sp. biomass (kg)" = "Dasypus_sp__kg",
                                            "Eira barbara biomass (kg)" = "Eira_barbara_kg",
                                            "Euphractus sexcinctus biomass (kg)" = "Euphractus_sexcinctus_kg",
                                            "Leopardus guttulus biomass (kg)" = "Leopardus_guttulus_kg",
                                            "Leopardus pardalis biomass (kg)" = "Leopardus_pardalis_kg",
                                            "Leopardus wiedii biomass (kg)" = "Leopardus_wiedii_kg",
                                            "Leopardus sp. biomass (kg)" = "Leopardus_sp__kg",
                                            "Mazama sp. biomass (kg)" = "Mazama_sp__kg",
                                            "Myrmecophaga tridactyla biomass (kg)" = "Myrmecophaga_tridactyla_kg",
                                            "Nasua nasua biomass (kg)" = "Nasua_nasua_kg",
                                            "Pecari tajacu biomass (kg)" = "Pecari_tajacu_kg",
                                            "Puma concolor biomass (kg)" = "Puma_concolor_kg",
                                            "Puma yagouaroundi biomass (kg)" = "Puma_yagouaroundi_kg",
                                            "Sylvilagus brasiliensis biomass (kg)" = "Sylvilagus_brasiliensis_kg",
                                            "Tamandua tetradactyla biomass (kg)" = "Tamandua_tetradactyla_kg",
                                            "Tapirus terrestris biomass (kg)" = "Tapirus_terrestris_kg",
                                            "Tayassu pecari" = "Tayassu_pecari_kg",
                                            "Cabassous sp. biomass (kg)" = "Cabassous_sp__kg_cam_effort",
                                            "Cuniculus paca biomass (kg)" = "Cuniculus_paca_kg_cam_effort",
                                            "Dasyprocta leporina biomass (kg)" = "Dasyprocta_leporina_kg_cam_effort",
                                            "Dasypus novemcinctus biomass (kg)" = "Dasypus_novemcinctus_kg_cam_effort",
                                            "Dasypus sp. biomass (kg)" = "Dasypus_sp__kg_cam_effort",
                                            "Eira barbara biomass (kg)" = "Eira_barbara_kg_cam_effort",
                                            "Euphractus sexcinctus biomass (kg)" = "Euphractus_sexcinctus_kg_cam_effort",
                                            "Leopardus guttulus biomass (kg)" = "Leopardus_guttulus_kg_cam_effort",
                                            "Leopardus pardalis biomass (kg)" = "Leopardus_pardalis_kg_cam_effort",
                                            "Leopardus wiedii biomass (kg)" = "Leopardus_wiedii_kg_cam_effort",
                                            "Leopardus sp. biomass (kg)" = "Leopardus_sp__kg_cam_effort",
                                            "Mazama sp. biomass (kg)" = "Mazama_sp__kg_cam_effort",
                                            "Myrmecophaga tridactyla biomass (kg)" = "Myrmecophaga_tridactyla_kg_cam_effort",
                                            "Nasua nasua biomass (kg)" = "Nasua_nasua_kg_cam_effort",
                                            "Pecari tajacu biomass (kg)" = "Pecari_tajacu_kg_cam_effort",
                                            "Puma concolor biomass (kg)" = "Puma_concolor_kg_cam_effort",
                                            "Puma yagouaroundi biomass (kg)" = "Puma_yagouaroundi_kg_cam_effort",
                                            "Sylvilagus brasiliensis biomass (kg)" = "Sylvilagus_brasiliensis_kg_cam_effort",
                                            "Tamandua tetradactyla biomass (kg)" = "Tamandua_tetradactyla_kg_cam_effort",
                                            "Tapirus terrestris biomass (kg)" = "Tapirus_terrestris_kg_cam_effort",
                                            "Tayassu pecari biomass (kg)" = "Tayassu_pecari_kg_cam_effort",
                                            "Cabassous sp. biomass mean time in plot (seconds)" = "Cabassous_sp__mean_time_in_plot",
                                            "Cuniculus paca biomass mean time in plot (seconds)" = "Cuniculus_paca_mean_time_in_plot",
                                            "Dasyprocta leporina biomass mean time in plot (seconds)" = "Dasyprocta_leporina_mean_time_in_plot",
                                            "Dasypus novemcinctus biomass mean time in plot (seconds)" = "Dasypus_novemcinctus_mean_time_in_plot",
                                            "Dasypus sp. biomass mean time in plot (seconds)" = "Dasypus_sp__mean_time_in_plot",
                                            "Eira barbara biomass mean time in plot (seconds)" = "Eira_barbara_mean_time_in_plot",
                                            "Euphractus sexcinctus biomass mean time in plot (seconds)" = "Euphractus_sexcinctus_mean_time_in_plot",
                                            "Leopardus guttulus biomass mean time in plot (seconds)" = "Leopardus_guttulus_mean_time_in_plot",
                                            "Leopardus pardalis biomass mean time in plot (seconds)" = "Leopardus_pardalis_mean_time_in_plot",
                                            "Leopardus wiedii biomass mean time in plot (seconds)" = "Leopardus_wiedii_mean_time_in_plot",
                                            "Leopardus sp. biomass mean time in plot (seconds)" = "Leopardus_sp__mean_time_in_plot",
                                            "Mazama sp. biomass mean time in plot (seconds)" = "Mazama_sp__mean_time_in_plot",
                                            "Myrmecophaga tridactyla biomass mean time in plot (seconds)" = "Myrmecophaga_tridactyla_mean_time_in_plot",
                                            "Nasua nasua biomass mean time in plot (seconds)" = "Nasua_nasua_mean_time_in_plot",
                                            "Pecari tajacu biomass mean time in plot (seconds)" = "Pecari_tajacu_mean_time_in_plot",
                                            "Puma concolor biomass mean time in plot (seconds)" = "Puma_concolor_mean_time_in_plot",
                                            "Puma_yagouaroundi biomass mean time in plot (seconds)" = "Puma_yagouaroundi_mean_time_in_plot",
                                            "Sylvilagus brasiliensis biomass mean time in plot (seconds)" = "Sylvilagus_brasiliensis_mean_time_in_plot",
                                            "Tamandua tetradactyla biomass mean time in plot (seconds)" = "Tamandua_tetradactyla_mean_time_in_plot",
                                            "Tapirus terrestris biomass mean time in plot (seconds)" = "Tapirus_terrestris_mean_time_in_plot",
                                            "Tayassu_pecari biomass mean time in plot (seconds)" = "Tayassu_pecari_mean_time_in_plot",
                                            "Medium and large-sized mammals body mass (kg)" = "ml_body_size_kg",
                                            "Herbivore body mass (kg)" = "hbvr_body_size_kg"), 
                                selected = "Latitude"),
                    
                    # Select variable for x-axis
                    selectInput(inputId = "x", 
                                label = "X-axis:",
                                choices = c("Plots" = "Plots", 
                                            "Longitude" = "Longitude",
                                            "Elevation (m)" = "Elevation",
                                            "Inclination (°)" = "Inclination",
                                            "Bearing (°)" = "Bearing",
                                            "Seedlings richness" = "Richness",
                                            "Seedlings abundance" = "Abundance",
                                            "Seedlings density" = "Density",
                                            "Shannon index diversity" = "D_Shannon",
                                            "Simpson index diversity" = "D_Simpson",
                                            "Canopy cover (%)" = "Canopy_cover",
                                            "Total adult trees outside plots" = "N_M_Trees_adult",
                                            "Total adult Euterpe edulis outside plots" = "N_M_Eedulis_adult",
                                            "Functional richness" = "FRic",
                                            "Functional evenness" = "FEve",
                                            "Functional diversity" = "FDiv",
                                            "Functional dispersion" = "FDis",
                                            "Rao's Quadratic Entropy - Functional diversity index" = "Rao",
                                            "Leaf thickness" = "leaf_thickness",
                                            "Seed mass" = "seed_mass",
                                            "Leaf area" = "leaf_area",
                                            "Specific leaf area" = "sla",
                                            "Seed length" = "seed_length",
                                            "Carbon and nitrogen ratio" = " carbon_nitro",
                                            "Total leaf damage index" = "leaf_demage",
                                            "Leaf damage index by external chewer" = "ME",
                                            "Leaf damage index by internal chewer" = "MI",
                                            "Leaf damage index by pathogens" = "PAT",
                                            "Leaf damage index by miners" = "MIN",
                                            "Leaf damage index by galls" = "GAL", 
                                            "Total Euterpe edulis seed offered" = "Ed_seeds_available",
                                            "Total Euterpe edulis seed preyed" = "Ed_seeds_preyed",
                                            "Total cameras trap efforts (hours) (seeds predation)" = "Ed_predation_efforts_hours",
                                            "Green House Gases Mean replicates" = "GHG_Rep",
                                            "Mean CH4" = "GHG_CH4",
                                            "Mean CO2 (mg)" = "GHG_CO2",
                                            "Mean N2O (mg)" = "GHG_N2O",
                                            "pH in water" = "pH_H2O",
                                            "pH in Calcium Chloride" = "pH_CaCl2",
                                            "Sum of the bases Ca2+, Mg2+, K+, Na+" = "SB",
                                            "Cation exchange capacity" = "CEC",
                                            "Base saturation" = "V",
                                            "Soil aluminum saturation" = "m",
                                            "Phosphorus Mehlich 1" = "P",
                                            "Potassium Mehlich 1" = "K",
                                            "Calcium KCl 1 mol.L-¹" = "Ca",
                                            "Magnesium KCl 1 mol.L-¹" = "Mg",
                                            "Aluminum KCl 1 mol.L-¹" = "Al",
                                            "Potencial acidity Calcium Acetate" = "H_Al",
                                            "Organic matter - Sodium Dicromate solution in Sulphuric acid determined by colorimetry" = "OM",
                                            "Total sand content (Buyoucos, densimeter)" = "Total_sand",
                                            "Silt content (Buyoucos, densimeter)" = "Silt",
                                            "Clay content (Buyoucos, densimeter)" = "Clay",
                                            "Levels of sand and clay content" = "Texture",
                                            "Total camera trap effort (day)" = "effort_cam_day_summed",
                                            "Total species richness" = "ttl_spp_rich",
                                            "Total medium and large-sized mammals species richness" = "med_lar_mamm_spp_rich",
                                            "Total small mammals species richness" = "small_mamm_spp_rich",
                                            "Total birds species richness" = "birds_spp_rich",
                                            "Total functional group richness" = "ttl_fg_rich",
                                            "Total medium and large-sized mammals functional group richness" = "med_lar_mamm_fg_rich",
                                            "Total small mammals functional group richness" = "small_mamm_fg_rich",
                                            "Total birds functional group richness" = "birds_fg_rich",
                                            "Birds functional group 1 individual frequency" = "birds_1_ttl_abnd",
                                            "Birds functional group 2 individual frequency" = "birds_2_ttl_abnd",
                                            "Birds functional group 3 individual frequency" = "birds_3_ttl_abnd",
                                            "Birds functional group 4 individual frequency" = "birds_4_ttl_abnd",
                                            "Herbivores functional group 1 individual frequency" = "herbivore_1_ttl_abnd",
                                            "Herbivores functional group 2 individual frequency" = "herbivore_2_ttl_abnd",
                                            "Herbivores functional group 3 individual frequency" = "herbivore_3_ttl_abnd",
                                            "Marsupials functional group 1 individual frequency" = "marsupial_1_ttl_abnd",
                                            "Marsupials functional group 2 individual frequency" = "marsupial_2_ttl_abnd",
                                            "Marsupials functional group 3 individual frequency" = "marsupial_3_ttl_abnd",
                                            "Mesopredator functional group 1 individual frequency" = "meso_1_ttl_abnd",
                                            "Others functional group 1 individual frequency" = "others_1_ttl_abnd",
                                            "Predators functional group 1 individual frequency" = "predator_1_ttl_abnd",
                                            "Predators functional group 2 individual frequency" = "predator_2_ttl_abnd",
                                            "Rodents functional group 1 individual frequency" = "rodent_1_ttl_abnd",
                                            "Rodents functional group 2 individual frequency" = "rodent_2_ttl_abnd",
                                            "Rodents functional group 3 individual frequency" = "rodent_3_ttl_abnd",
                                            "Rodents functional group 4 individual frequency" = "rodent_4_ttl_abnd",
                                            "All medium and large-sized mammals functional group individual frequency" = "all_med_lar_abn",
                                            "All small mammals functional group individual frequency" = "all_small_abn",
                                            "All birds functional group individual frequency" = "all_birds_abn",
                                            "Cabassous sp. individual frequency" = "Cabassous_sp__ttl_abnd",
                                            "Cuniculus paca individual frequency"= "Cuniculus_paca_ttl_abnd",
                                            "Dasyprocta leporina individual frequency"= "Dasyprocta_leporina_ttl_abnd",
                                            "Dasypus novemcinctus individual frequency" = "Dasypus_novemcinctus_ttl_abnd",
                                            "Dasypus_sp. individual frequency" = "Dasypus_sp__ttl_abnd",
                                            "Eira barbara individual frequency" = "Eira_barbara_ttl_abnd",
                                            "Euphractus sexcinctus individual frequency" = "Euphractus_sexcinctus_ttl_abnd",
                                            "Leopardus guttulus individual frequency" = "Leopardus_guttulus_ttl_abnd",
                                            "Leopardus pardalis individual frequency" = "Leopardus_pardalis_ttl_abnd",
                                            "Leopardus wiedii individual frequency" = "Leopardus_wiedii_ttl_abnd",
                                            "Leopardus sp. individual frequency" = "Leopardus_sp__ttl_abnd",
                                            "Mazama sp. individual frequency" = "Mazama_sp__ttl_abnd",
                                            "Myrmecophaga tridactyla individual frequency" = "Myrmecophaga_tridactyla_ttl_abnd",
                                            "Nasua nasua individual frequency" = "Nasua_nasua_ttl_abnd",
                                            "Pecari tajacu individual frequency" = "Pecari_tajacu_ttl_abnd",
                                            "Puma concolor individual frequency" = "Puma_concolor_ttl_abnd",
                                            "Puma yagouaroundi individual frequency" = "Puma_yagouaroundi_ttl_abnd",
                                            "Sylvilagus brasiliensis individual frequency" = "Sylvilagus_brasiliensis_ttl_abnd",
                                            "Tamandua tetradactyla individual frequency" = "Tamandua_tetradactyla_ttl_abnd",
                                            "Tapirus terrestris individual frequency" = "Tapirus_terrestris_ttl_abnd",
                                            "Tayassu pecari individual frequency" = "Tayassu_pecari_ttl_abnd",
                                            "Birds functional group 1 biomass (kg)" = "birds_1_fg_kg",
                                            "Birds functional group 2 biomass (kg)"= "birds_2_fg_kg",
                                            "Birds functional group 3 biomass (kg)" = "birds_3_fg_kg",
                                            "Birds functional group 4 biomass (kg)" = "birds_4_fg_kg",
                                            "Birds herbivore group 1 biomass (kg)" = "herbivore_1_fg_kg",
                                            "Birds herbivore group 2 biomass (kg)" = "herbivore_2_fg_kg",
                                            "Birds herbivore group 3 biomass (kg)" = "herbivore_3_fg_kg",
                                            "Marsupial functional group 1 biomass (kg)" = "marsupial_1_fg_kg",
                                            "Marsupial functional group 2 biomass (kg)" = "marsupial_2_fg_kg",
                                            "Marsupial functional group 3 biomass (kg)" = "marsupial_3_fg_kg",
                                            "Mesopredator functional group 1 biomass (kg)" = "meso_1_fg_kg",
                                            "Others functional group 1 biomass (kg)" = "others_1_fg_kg",
                                            "Predator functional group 1 biomass (kg)" = "predator_1_fg_kg",
                                            "Predator functional group 2 biomass (kg)" = "predator_2_fg_kg",
                                            "Rodent functional group 1 biomass (kg)" = "rodent_1_fg_kg",
                                            "Rodent functional group 2 biomass (kg)" = "rodent_2_fg_kg",
                                            "Rodent functional group 3 biomass (kg)" = "rodent_3_fg_kg",
                                            "Rodent functional group 4 biomass (kg)" = "rodent_4_fg_kg",
                                            "Total medium and large-sized mammals functional group biomass (kg)" = "all_med_lar_bmss_kg",
                                            "Total small mammals functional group biomass (kg)" = "all_small_bmss_kg",
                                            "Total birds functional group biomass (kg)" = "all_birds_bmss_kg",
                                            "Birds functional group 1 biomass (kg) by camera efforts (day)" = "birds_1_fg_kg_cam_effort",
                                            "Birds functional group 2 biomass (kg) by camera efforts (day)"= "birds_2_fg_kg_cam_effort",
                                            "Birds functional group 3 biomass (kg) by camera efforts (day)" = "birds_3_fg_kg_cam_effort",
                                            "Birds functional group 4 biomass (kg) by camera efforts (day)" = "birds_4_fg_kg_cam_effort",
                                            "Herbivore functional group 1 biomass (kg) by camera efforts (day)" = "herbivore_1_fg_kg_cam_effort",
                                            "Herbivore functional group 2 biomass (kg) by camera efforts (day)" = "herbivore_2_fg_kg_cam_effort",
                                            "Herbivore functional group 3 biomass (kg) by camera efforts (day)" = "herbivore_3_fg_kg_cam_effort",
                                            "Marsupials functional group 1 biomass (kg) by camera efforts (day)" = "marsupial_1_fg_kg_cam_effort",
                                            "Marsupials functional group 2 biomass (kg) by camera efforts (day)" = "marsupial_2_fg_kg_cam_effort",
                                            "Marsupials functional group 3 biomass (kg) by camera efforts (day)" = "marsupial_3_fg_kg_cam_effort",
                                            "Mesopredator functional group 1 biomass (kg) by camera efforts (day)" = "meso_1_fg_kg_cam_effort",
                                            "Others functional group 1 biomass (kg) by camera efforts (day)" = "others_1_fg_kg_cam_effort",
                                            "Predators functional group 1 biomass (kg) by camera efforts (day)" = "predator_1_fg_kg_cam_effort",
                                            "Predators functional group 2 biomass (kg) by camera efforts (day)" = "predator_2_fg_kg_cam_effort",
                                            "Rodents functional group 1 biomass (kg) by camera efforts (day)" = "rodent_1_fg_kg_cam_effort",
                                            "Rodents functional group 2 biomass (kg) by camera efforts (day)" = "rodent_2_fg_kg_cam_effort",
                                            "Rodents functional group 3 biomass (kg) by camera efforts (day)" = "rodent_3_fg_kg_cam_effort",
                                            "Rodents functional group 4 biomass (kg) by camera efforts (day)" = "rodent_4_fg_kg_cam_effort",
                                            "Total medium and large-sized mammals functional group biomass (kg) by camera efforts (day)" = "all_med_lar_bmss_kg_cam_effort",
                                            "Total small mammals functional group biomass (kg) by camera efforts (day)" = "all_small_bmss_kg_cam_effort",
                                            "Total birds functional group biomass (kg) by camera efforts (day)" = "all_birds_bmss_kg_cam_effort",
                                            "Cabassous sp. biomass (kg)" = "Cabassous_sp__kg",
                                            "Cuniculus paca biomass (kg)" = "Cuniculus_paca_kg",
                                            "Dasyprocta leporina biomass (kg)" = "Dasyprocta_leporina_kg",
                                            "Dasypus novemcinctus biomass (kg)" = "Dasypus_novemcinctus_kg",
                                            "Dasypus sp. biomass (kg)" = "Dasypus_sp__kg",
                                            "Eira barbara biomass (kg)" = "Eira_barbara_kg",
                                            "Euphractus sexcinctus biomass (kg)" = "Euphractus_sexcinctus_kg",
                                            "Leopardus guttulus biomass (kg)" = "Leopardus_guttulus_kg",
                                            "Leopardus pardalis biomass (kg)" = "Leopardus_pardalis_kg",
                                            "Leopardus wiedii biomass (kg)" = "Leopardus_wiedii_kg",
                                            "Leopardus sp. biomass (kg)" = "Leopardus_sp__kg",
                                            "Mazama sp. biomass (kg)" = "Mazama_sp__kg",
                                            "Myrmecophaga tridactyla biomass (kg)" = "Myrmecophaga_tridactyla_kg",
                                            "Nasua nasua biomass (kg)" = "Nasua_nasua_kg",
                                            "Pecari tajacu biomass (kg)" = "Pecari_tajacu_kg",
                                            "Puma concolor biomass (kg)" = "Puma_concolor_kg",
                                            "Puma yagouaroundi biomass (kg)" = "Puma_yagouaroundi_kg",
                                            "Sylvilagus brasiliensis biomass (kg)" = "Sylvilagus_brasiliensis_kg",
                                            "Tamandua tetradactyla biomass (kg)" = "Tamandua_tetradactyla_kg",
                                            "Tapirus terrestris biomass (kg)" = "Tapirus_terrestris_kg",
                                            "Tayassu pecari" = "Tayassu_pecari_kg",
                                            "Cabassous sp. biomass (kg)" = "Cabassous_sp__kg_cam_effort",
                                            "Cuniculus paca biomass (kg)" = "Cuniculus_paca_kg_cam_effort",
                                            "Dasyprocta leporina biomass (kg)" = "Dasyprocta_leporina_kg_cam_effort",
                                            "Dasypus novemcinctus biomass (kg)" = "Dasypus_novemcinctus_kg_cam_effort",
                                            "Dasypus sp. biomass (kg)" = "Dasypus_sp__kg_cam_effort",
                                            "Eira barbara biomass (kg)" = "Eira_barbara_kg_cam_effort",
                                            "Euphractus sexcinctus biomass (kg)" = "Euphractus_sexcinctus_kg_cam_effort",
                                            "Leopardus guttulus biomass (kg)" = "Leopardus_guttulus_kg_cam_effort",
                                            "Leopardus pardalis biomass (kg)" = "Leopardus_pardalis_kg_cam_effort",
                                            "Leopardus wiedii biomass (kg)" = "Leopardus_wiedii_kg_cam_effort",
                                            "Leopardus sp. biomass (kg)" = "Leopardus_sp__kg_cam_effort",
                                            "Mazama sp. biomass (kg)" = "Mazama_sp__kg_cam_effort",
                                            "Myrmecophaga tridactyla biomass (kg)" = "Myrmecophaga_tridactyla_kg_cam_effort",
                                            "Nasua nasua biomass (kg)" = "Nasua_nasua_kg_cam_effort",
                                            "Pecari tajacu biomass (kg)" = "Pecari_tajacu_kg_cam_effort",
                                            "Puma concolor biomass (kg)" = "Puma_concolor_kg_cam_effort",
                                            "Puma yagouaroundi biomass (kg)" = "Puma_yagouaroundi_kg_cam_effort",
                                            "Sylvilagus brasiliensis biomass (kg)" = "Sylvilagus_brasiliensis_kg_cam_effort",
                                            "Tamandua tetradactyla biomass (kg)" = "Tamandua_tetradactyla_kg_cam_effort",
                                            "Tapirus terrestris biomass (kg)" = "Tapirus_terrestris_kg_cam_effort",
                                            "Tayassu pecari biomass (kg)" = "Tayassu_pecari_kg_cam_effort",
                                            "Cabassous sp. biomass mean time in plot (seconds)" = "Cabassous_sp__mean_time_in_plot",
                                            "Cuniculus paca biomass mean time in plot (seconds)" = "Cuniculus_paca_mean_time_in_plot",
                                            "Dasyprocta leporina biomass mean time in plot (seconds)" = "Dasyprocta_leporina_mean_time_in_plot",
                                            "Dasypus novemcinctus biomass mean time in plot (seconds)" = "Dasypus_novemcinctus_mean_time_in_plot",
                                            "Dasypus sp. biomass mean time in plot (seconds)" = "Dasypus_sp__mean_time_in_plot",
                                            "Eira barbara biomass mean time in plot (seconds)" = "Eira_barbara_mean_time_in_plot",
                                            "Euphractus sexcinctus biomass mean time in plot (seconds)" = "Euphractus_sexcinctus_mean_time_in_plot",
                                            "Leopardus guttulus biomass mean time in plot (seconds)" = "Leopardus_guttulus_mean_time_in_plot",
                                            "Leopardus pardalis biomass mean time in plot (seconds)" = "Leopardus_pardalis_mean_time_in_plot",
                                            "Leopardus wiedii biomass mean time in plot (seconds)" = "Leopardus_wiedii_mean_time_in_plot",
                                            "Leopardus sp. biomass mean time in plot (seconds)" = "Leopardus_sp__mean_time_in_plot",
                                            "Mazama sp. biomass mean time in plot (seconds)" = "Mazama_sp__mean_time_in_plot",
                                            "Myrmecophaga tridactyla biomass mean time in plot (seconds)" = "Myrmecophaga_tridactyla_mean_time_in_plot",
                                            "Nasua nasua biomass mean time in plot (seconds)" = "Nasua_nasua_mean_time_in_plot",
                                            "Pecari tajacu biomass mean time in plot (seconds)" = "Pecari_tajacu_mean_time_in_plot",
                                            "Puma concolor biomass mean time in plot (seconds)" = "Puma_concolor_mean_time_in_plot",
                                            "Puma_yagouaroundi biomass mean time in plot (seconds)" = "Puma_yagouaroundi_mean_time_in_plot",
                                            "Sylvilagus brasiliensis biomass mean time in plot (seconds)" = "Sylvilagus_brasiliensis_mean_time_in_plot",
                                            "Tamandua tetradactyla biomass mean time in plot (seconds)" = "Tamandua_tetradactyla_mean_time_in_plot",
                                            "Tapirus terrestris biomass mean time in plot (seconds)" = "Tapirus_terrestris_mean_time_in_plot",
                                            "Tayassu_pecari biomass mean time in plot (seconds)" = "Tayassu_pecari_mean_time_in_plot",
                                            "Medium and large-sized mammals body mass (kg)" = "ml_body_size_kg",
                                            "Herbivore body mass (kg)" = "hbvr_body_size_kg"),
                                selected = "Longitude"),
                    
                    # Select variable for color
                    selectInput(inputId = "z", 
                                label = "Color by:",
                                choices = c("Treatment" = "Treatment",
                                            "Location" = "Location"),
                                selected = "Treatment"),
                    
                    
                    # Select the filter function

                    
                    selectInput(inputId = "Location",
                                label = "Sampled area (s):",
                                choices = c("Cardoso island" = "CAR", 
                                            "Carlos Botelho" = "CBO", 
                                            "Itamambuca" = "ITA", 
                                            "Vargem Grande" = "VGM"),
                                selected = c("CAR","CBO","ITA","VGM"),
                                multiple = TRUE),
                    
                    # Select year
                    selectInput(inputId = "Date",
                                label = "Chose the year range:",
                                choices = c(2017,2019),
                                selected = c(2017,2019),
                                multiple = TRUE),
                    
                    # Enter text for plot title, only when other inputs are updated
                    textInput(inputId = "plot_title", label = "Plot title",placeholder = "Enter text to be used as plot title"),
                    textInput("x_axis",label = "Plot X axis text",placeholder = "Enter text to be used as x-axis title"),
                    textInput("y_axis",label = "Plot Y axis text",placeholder = "Enter text to be used as y-axis title"),
                    
                    sliderInput(inputId = "alpha", 
                                label = "Alpha:",
                                min = 0, max = 1, 
                                value = 0.5)),
                  
                  fluidRow(box(plotOutput(outputId = "scatterplot"), title = "Linear regression", status = "primary",
                               background = "olive", collapsible = FALSE))
                  
                  #red, yellow, aqua, blue, light-blue, green, navy, teal, olive, lime, orange, fuchsia, purple, maroon, black.
                )
       ),
       
       tabItem(tabName  = "home",
               includeMarkdown("home/home_description2.Rmd"),
               img(src = "agencies00.png"),
               includeMarkdown("home/shiny_description.Rmd")), 
       
       tabItem(tabName  = "map",
               h1("Sampled areas"),
               leafletOutput(outputId = "mymap",width="100%",height="800px")
               ),
       
       tabItem(tabName  = "description",
               includeMarkdown("area/areas_description.Rmd"),
               includeMarkdown("area/santa_virginia.Rmd"),
               img(src = "ita_01.png"),
               img(src = "anta_01.jpg"),
               img(src = "queixada_01.jpg"),
               img(src = "queixada_02.jpg"),
               img(src = "ita_02.jpg"),
               img(src = "ita_05.jpg"),
               img(src = "ita_06.jpg"),
               img(src = "ita_07.jpg"),
               img(src = "ita_10.jpg"),
               img(src = "ita_11.jpg"),
               img(src = "ita_12.jpg"),
               img(src = "ita_13.jpg"),
               img(src = "ita_14.jpg"),
               includeMarkdown("area/cardoso_island.Rmd"),
               img(src = "queixada_02.jpg"),
               img(src = "car_02.jpg"),
               img(src = "car_01.jpeg"),
               img(src = "car_05.jpg"),
               img(src = "car_06.jpg"),
               img(src = "car_07.jpg"),
               includeMarkdown("area/carlos_botelho.Rmd"),
               img(src = "anta_02.jpg"),
               img(src = "cbo_02.jpg"),
               img(src = "cbo_01.jpg"),
               img(src = "cbo_05.jpg"),
               img(src = "cbo_06.jpg"),
               img(src = "cbo_07.jpg"),
               img(src = "cbo_08.jpg"),
               img(src = "cbo_09.jpg"),
               includeMarkdown("area/vargem_grande.Rmd"),
               img(src = "vgm_04.jpg"),
               img(src = "vgm_01.png"),
               img(src = "vgm_03.jpg"),
               img(src = "vgm_06.jpg"),
               img(src = "vgm_07.jpg"),
               img(src = "vgm_08.jpg"),
               img(src = "vgm_09.jpg"),
               img(src = "vgm_10.jpg")

       ),
       
       tabItem(tabName  = "datatable",
               h1("All the biotic and abiotic variables"),
               h5("The filter applied in the Data exploration tab will automatically be applied here in this table"),
               
               # Show data table
               checkboxInput(inputId = "show_data",
                             label = "Show data table",
                             value = TRUE),
               
               DT::dataTableOutput(outputId = "biotatable"),
               downloadButton("downloadData", "Download Data"),
               downloadButton("downloadData1", "Download 10-year seedlings sampled"),
               includeMarkdown("data/metadata.Rmd"),
               tags$head(tags$style("#biotatable table {background-color: #4d8cbb; }", media="screen", type="text/css"))
       ),
       
       tabItem(tabName  = "sampling_design",
               includeMarkdown("plots/plots.Rmd"),
               img(src = "plot.png"),
               img(src = "plot0.jpg"),
               img(src = "plot1.jpg"),
               img(src = "plot2.jpg"),
               img(src = "plot3.jpg"),
               img(src = "plot5.jpg"),
               img(src = "plot6.jpg"),
               img(src = "plot7.jpg"),
               img(src = "plot8.jpeg"),
               img(src = "plot9.jpeg")
               ),
       
       tabItem(tabName  = "fielworks",
               img(src = "field.jpg"),
               img(src = "field0.jpeg"),
               img(src = "field01.jpg"),
               img(src = "field2.2.jpeg"),
               img(src = "field03.jpeg"),
               img(src = "field04.jpeg"),
               img(src = "field05.jpeg"),
               img(src = "field06.jpg"),
               img(src = "field07.jpg"),
               img(src = "field08.jpg"),
               img(src = "field09.jpg"),
               img(src = "field10.jpeg"),
               img(src = "field11.jpeg"),
               img(src = "field12.jpeg"),
               img(src = "field13.jpeg"),
               img(src = "field14.jpg"),
               img(src = "field15.jpg"),
               img(src = "field16.jpg"),
               img(src = "field17.jpg"),
               img(src = "field18.jpg"),
               img(src = "field19.jpg"),
               img(src = "field02.jpg"),
               img(src = "field20.jpeg"),
               img(src = "field21.jpeg"),
               img(src = "field22.jpg"),
               img(src = "field23.jpg"),
               img(src = "field24.jpg"),
               img(src = "field25.jpg"),
               img(src = "field26.jpg"),
               img(src = "field27.jpg"),
               img(src = "field28.jpg"),
               img(src = "field29.jpeg"),
               img(src = "field30.jpeg"),
               img(src = "field31.jpeg"),
               img(src = "field32.jpeg"),
               img(src = "field33.jpg"),
               img(src = "field34.jpg"),
               img(src = "field35.jpeg"),
               img(src = "field36.jpeg"),
               img(src = "field37.jpeg"),
               img(src = "field38.jpeg"),
               img(src = "field39.jpeg"),
               img(src = "field40.jpeg"),
               img(src = "field41.jpeg"),
               img(src = "field42.jpg"),
               img(src = "field43.jpg"),
               img(src = "field44.jpg"),
               img(src = "field45.jpg"),
               img(src = "field46.jpg"),
               img(src = "field47.jpg"),
               img(src = "field48.jpg"),
               img(src = "field49.jpg"),
               img(src = "field51.jpeg"),
               img(src = "field52.jpeg"),
               img(src = "field53.jpeg"),
               img(src = "field54.jpeg"),
               img(src = "field100.jpeg")
               ), 
       
       tabItem(tabName  = "camera_traps",
               includeMarkdown("cam_trap/camera_trap.Rmd")
               ), 
       
       tabItem(tabName  = "social_media",
               img(src = "social.jpg"),
               img(src = "social00.jpg"),
               img(src = "social_01.jpeg"),
               img(src = "social_02.jpg"),
               img(src = "social_03.jpg"),
               img(src = "social_04.jpeg"),
               img(src = "social_05.jpg"),
               img(src = "social_06.jpg"),
               img(src = "social_07.jpg"),
               img(src = "social_08.jpg"),
               img(src = "social_09.jpg"),
               img(src = "social_10.jpeg"),
               img(src = "social_11.jpg"),
               img(src = "social_12.jpg"),
               img(src = "social_13.jpg"),
               img(src = "social_14.jpeg")
       ), 
       
       tabItem(tabName  = "media",
               includeMarkdown("social/social.Rmd")), 
       
       tabItem(tabName  = "publications",
               includeMarkdown("papers/papers5.Rmd"),
               img(src = "papers5.jpg"),
               includeMarkdown("papers/papers4.Rmd"),
               img(src = "papers4.jpg"),
               includeMarkdown("papers/papers3.Rmd"),
               includeMarkdown("papers/papers2.Rmd"),
               img(src = "papers2.jpg"),
               includeMarkdown("papers/papers1.Rmd")
               ), 
       
       tabItem(tabName  = "contacts",
               includeMarkdown("contacts/contact.Rmd"),
               img(src = "mauro.jpg"),
               includeMarkdown("contacts/mauro.Rmd"),
               includeMarkdown("contacts/description.Rmd"),
               img(src = "pedro.jpg"),
               includeMarkdown("contacts/pedro.Rmd"),
               img(src = "tsai.png"),
               includeMarkdown("contacts/tsai.Rmd"),
               img(src = "tadeu.jpg"),
               includeMarkdown("contacts/tadeu.Rmd"),
               img(src = "valesca.png"),
               includeMarkdown("contacts/valesca.Rmd"),
               img(src = "nacho.jpg"),
               includeMarkdown("contacts/nacho.Rmd"),
               img(src = "claudinha.png"),
               includeMarkdown("contacts/claudinha.Rmd"),
               img(src = "carine.png"),
               includeMarkdown("contacts/carine.Rmd"),
               img(src = "fernando.jpg"),
               includeMarkdown("contacts/fernando.Rmd"),
               img(src = "paula.jpg"),
               includeMarkdown("contacts/paula.Rmd"),
               img(src = "yuri.jpeg"),
               includeMarkdown("contacts/yuri.Rmd"),
               img(src = "leticia.png"),
               includeMarkdown("contacts/leticia.Rmd"),
               img(src = "fulbert.png"),
               includeMarkdown("contacts/fulbert.Rmd"),
               img(src = "jade.png"),
               includeMarkdown("contacts/jade.Rmd"),
               img(src = "natalia.png"),
               includeMarkdown("contacts/natalia.Rmd"),
               img(src = "sergio.png"),
               includeMarkdown("contacts/sergio.Rmd"),
               img(src = "urucum.png"),
               includeMarkdown("contacts/urucum.Rmd")
               ) 
       
      )
    ) #fech dashboardbody
   )
)


