
## **Plots desing** !
___________________________________________________________________________________________________

___________________________________________________________________________________________________
In 2009, 15 sets of open control plots and experimental exclusion plots were established at Carlos Botelho State Park. The plots were 5 meters long and 3 meters wide, covering an area of 15 square meters each. In 2010, similar plots were set up in the other regions. Over the years, some of the plots were lost due to fallen trees. The dataset available here includes a total of 86 plots, with 9 paired plots in Santa Virgínia/Itamabuca, 12 in Cardoso Island, 10 in Carlos Botelho, and 12 in Vargem Grande. In every region, the plots were established following the same methodology.

To minimize spatial autocorrelation, each pair of plots is located at least 200 meters apart from each other. The exclusion plots are enclosed by a 1.6-meter-high metal fence with a 5 cm wire mesh, which restricts access to all land mammals except for small rodents and marsupials. The control plots are open and their area is marked by pipes and fishing line at a height of 1 meter. Open and closed plots are separated by a distance of 2-7 meters, ensuring consistency between microenvironments. We maintain a 0.5-meter border inside each plot to facilitate access while limiting disturbance and false outcomes resulting from, for instance, the use of fences as perches by birds and edge effects.

At the beginning of the experiment, every plot was subdivided into eight 1 m2 subplots, and on three of them (selected at random) all seedlings between 0.1 and 1 m height were identified and marked individually. Subsequent regular surveys of the same subplots were carried out every 6 months, and on every occasion all new seedlings were identified and marked, and the fate of previously marked seedlings checked.

Due to the COVID-19 pandemic, our monitoring was temporarily discontinued and resumed in 2023. The updated date is not yet available in this database. Please contact one of the project heads for access.

___________________________________________________________________________________________________

___________________________________________________________________________________________________
