
## **Works published in scientific magazines**

___________________________________________________________________________________________________

___________________________________________________________________________________________________


[**Large mammalian herbivores modulate plant growth form diversity in a tropical rainforest**](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2745.13846)

**Abstract**

The world’s terrestrial biomes are broadly classified according to the dominant plant growth forms that define ecosystem structure and processes. Although the abundance and distribution of different plant growth forms can be strongly determined by factors such as climate and soil composition, large mammalian herbivores have a strong impact on plant communities, thus defaunation (the local or functional extinction of large animals) has the potential to alter the compositional structure of plant growth forms in natural ecosystems. Tropical rainforests sustain a high diversity of growth forms, including trees, palms, lianas, shrubs, herbs and bamboos, all of which play important ecosystem functions. Here, we experimentally evaluate how large mammalian herbivores affect the dominance, diversity and coexistence of these major tropical forest plant growth forms, by monitoring communities of saplings on the understorey in 43 paired exclusion plots in a long-term replicated exclusion experiment in the understorey of the Atlantic forest of Brazil. Over the course of 10 years large herbivore exclusion decreased diversity among growth forms, increased the absolute abundance of palms and trees (22% and 38% respectively) and increased the diversity of species within these two groups, to the detriment of other growth forms. Furthermore, all pairwise relationships between growth forms were positive on plots where herbivores had access, whereas several strong negative relationships emerged in plots where herbivores were excluded. This occurred despite strong background directional temporal trends affecting plant communities in both experimental treatments across the region.Our work indicates that the defaunation alters growth form dominance by favouring palms and trees while eroding diversity among growth forms and coexistence on a temporal scale. Large herbivore mammals promote diversity among growth forms, preventing the hyper-dominance of trees and palms, yet without supressing the diversity of species within growth forms. We argue that large herbivore mammals affect growth forms through several non-mutually exclusive mechanisms, including herbivory, seed dispersal and physical disturbance, as well as differential effects linked to the morphological and physiological adaptations of growth forms. We conclude that defaunation might lead to profound impacts on important ecosystem functions underpinned by growth form diversity, and result in vertical and horizontal structural simplification of tropical rainforests.


