
## **Works published in scientific magazines**

___________________________________________________________________________________________________

___________________________________________________________________________________________________


[**Causes and Consequences of Large-Scale Defaunation in the Atlantic Forest**](https://link.springer.com/chapter/10.1007%2F978-3-030-55322-7_14?fbclid=IwAR0uYfXQUqmzb5AXpN0D2XMZziXU96BSIj5HaFiEQO_f6Xdy5kW4dhs_8Hg)

**Abstract**

The Atlantic Forest of South America hosts one of the world’s most diverse and threatened tropical forest biota. After five centuries of European human expansion, most Atlantic Forest landscapes are archipelagos of small forest fragments surrounded by open-habitat matrices. In this chapter, we describe the causes and consequences of large-scale defaunation in the Atlantic Forest of South America. We identify and quantify the magnitude of the main anthropogenic drivers of defaunation and stimulate a debate on how to revert the loss of fauna to restore biodiversity and ecosystem functions and services. The magnitude of the impact of defaunation in the Atlantic Forest is hard to estimate, but we can predict that, at large scale, habitat loss, fragmentation, and degradation are the most common threats to terrestrial populations. Other threats vary in importance according to the taxonomic group. In general, apex predators, other carnivores, large-bodied mammals, and large herbivores were among the most defaunated functional groups and the loss of these animals has also a strong impact on the ecosystem services. Given the extent of the consequences of defaunation in the Atlantic Forest, mitigation strategies are imperative. Habitat restoration would clearly be effective in building space for defaunation mitigation but reversing the pervasive defaunation that occurred in the Atlantic Forest is by no means a straightforward task. Nonetheless, it will be fundamental to assure the persistence of the biodiversity in the Atlantic Forest remnants.


