## **Interviews and reports**

___________________________________________________________________________________________________

___________________________________________________________________________________________________

#### **English**

___________________________________________________________________________________________________

___________________________________________________________________________________________________


• [**Large mammals make soil more fertile in tropical forests**](https://www.britishecologicalsociety.org/large-mammals-make-soil-more-fertile-in-tropical-forests/)

___________________________________________________________________________________________________


• [**Nacho Villar: the challenges of experimentally resolving the functional roles of large tropical forest herbivores**](https://functionalecologists.com/2020/12/10/nacho-villar-the-challenges-of-experimentally-resolving-the-functional-roles-of-large-tropical-forest-herbivores/)

___________________________________________________________________________________________________


• [**Extinction of lowland tapir and white-lipped peccary would impair forest diversity**](https://www.eurekalert.org/pub_releases/2019-11/fda-eol110419.php)

___________________________________________________________________________________________________


• [**Where have all the animals gone?**](https://www.washingtonpost.com/news/achenblog/wp/2014/07/24/where-have-all-the-animals-gone/)

___________________________________________________________________________________________________


• [**Invertebrate numbers nearly halve as human population doubles**](https://phys.org/news/2014-07-invertebrate-halve-human-population.html)

___________________________________________________________________________________________________

___________________________________________________________________________________________________

#### **Portuguese**

___________________________________________________________________________________________________

___________________________________________________________________________________________________


• [**Frugivoria controla ciclo de nitrogênio em florestas tropicais**](https://www.biota.org.br/frugivoria-controla-ciclo-de-nitrogenio-em-florestas-tropicais/)

___________________________________________________________________________________________________


• [**Grandes mamíferos tornam solo da floresta mais fértil**](https://agencia.fapesp.br/grandes-mamiferos-tornam-solo-da-floresta-mais-fertil/34879/?fbclid=IwAR1kqTi6uHwtBs-biU9HZhy9cDdLiFDbFi7OFrVZn9hqugSJJppqSQ1ozGQ)

___________________________________________________________________________________________________


• [**Cientistas avaliam nova função ecológica de antas e queixadas em florestas**](https://registro.portaldacidade.com/noticias/regiao/cientistas-avaliam-nova-funcao-ecologica-de-antas-e-queixadas-em-florestas-0325)

___________________________________________________________________________________________________


• [**Atividades humanas afetam interações entre plantas e aves dispersoras de sementes**](https://agencia.fapesp.br/atividades-humanas-afetam-interacoes-entre-plantas-e-aves-dispersoras-de-sementes/32963/)

___________________________________________________________________________________________________


• [**Serra do Mar é uma das áreas mais preservadas da mata Atlântica**](http://g1.globo.com/globo-reporter/noticia/2018/06/serra-do-mar-e-uma-das-areas-mais-preservadas-de-mata-atlantica.html)

___________________________________________________________________________________________________


• [**Caça ilegal ameaça deixar Mata Atlântica desabitada**](https://www.oeco.org.br/noticias/caca-ilegal-ameaca-deixar-mata-atlantica-desabitada/)

___________________________________________________________________________________________________

___________________________________________________________________________________________________

#### **Spanish**

___________________________________________________________________________________________________

___________________________________________________________________________________________________


• [**Caza ilegal puede amenazar fauna del Bosque Atlántico**](https://www.scidev.net/america-latina/biodiversidad/noticias/caza-ilegal-puede-amenazar-fauna-del-bosque-atlantico.html)

___________________________________________________________________________________________________

___________________________________________________________________________________________________

